Romain/create fruit
mines-ap2022-groupe-3/agar.io pull request #22
Opened 2022-11-07 22:48 UTC by RomainGras

Génère des fruits à l'intérieur du screen

2022-11-09 15:48 UTC, RomainGras commented
resolve #2

2022-11-10 17:22 UTC, raphaelpra requested changes
Bon travail. Quelque retours pour améliorer cela.

2022-11-10 17:22 UTC, raphaelpra commented on main.py
> +def generate_random_fruit_position(position):
Dans l'absolue la position d'un fruit n'a pas de raison de dépendre de la position d'un blop -> lorsqu'on aura une version multi-joueur -> les fruits devront se générer indépendamment de la position du blop.

Il faut donc une logique a base de 
```
x, y = random.randint(0, M_WIDTH), random.randint(0, M_HEIGHT))
```
et afficher le fruit ssi il est dans l'écran. (du coup `inside_map` ne servira à rien)

2022-11-10 17:22 UTC, raphaelpra commented on main.py
> +    if pos_fruits == [] or (random.random() > 0.99 and len(pos_fruits) < 20):
Bonne pratique mettre `0.99` et `20` dans des variable globale (en prenant soin de bien les nommer).

2022-11-10 17:22 UTC, raphaelpra commented on main.py
> +col_fruits = []
Les 2 notions sont très imbriqués. Il est dommage de les séparer dans 2 listes (risques que les 2 listes diverges).

Proposition:
* avoir une liste `fruits = []` (voir même un `set`)
* chaque fruit est lui même un named tupple :
dans les imports :
```
from collections import namedtuple
Fruit = namedtuple("Fruit", "xy color")

# a utiliser ainsi : `f = Fruit(xy, color)` xy étant un V2 de pygame
```

2022-11-10 17:22 UTC, raphaelpra commented on main.py
> +        if (position + SCREEN // 2 - pos_fruit).length() < size:
Bien !

Il y a cependant un petit problème (il me semble), `position` correspond à la vrai position de l'objet (et non `position + SCREEN // 2`).

Du coup, je recommande cela : 
```suggestion
        if (position - pos_fruit).length() < size:
```

2022-11-10 17:22 UTC, raphaelpra commented on main.py
> +    blob_size = 20
Cela mérite une constante

2022-11-15 15:21 UTC, raphaelpra commented on main.py
> +        pg.draw.circle(screen, f.color, center, f.radius)
Le problème est ici !

`center` est le vecteur entre la position du blob est celle du fruit. Si tu veux la positionner correctement, tu la positionne par rapport au centre de l'écran. Du coup c'est ici qu'il faut rajouter ton `+ SCREEN_CENTER` ou `+ SCRENN // 2`

2022-11-15 15:21 UTC, raphaelpra commented on main.py
> +        if (position + SCREEN // 2 - pos_fruit).length() < size:
https://github.com/mines-ap2022-groupe-3/agar.io/pull/22#discussion_r1022927007

2022-11-25 14:39 UTC, raphaelpra approved these changes

2022-11-25 15:04 UTC, merged